import type { GroceryItem, Recipe } from '@/lib/types';
import { format, addDays } from 'date-fns';

const today = new Date();

export const mockGroceryItems: GroceryItem[] = [
  { id: 1, name: 'Avocado', category: 'Produce', quantity: 3, expiryDate: format(addDays(today, 2), 'yyyy-MM-dd') },
  { id: 2, name: 'Chicken Breast', category: 'Meat', quantity: 2, expiryDate: format(addDays(today, 1), 'yyyy-MM-dd') },
  { id: 3, name: 'Milk', category: 'Dairy', quantity: 1, expiryDate: format(addDays(today, 5), 'yyyy-MM-dd') },
  { id: 4, name: 'Cheddar Cheese', category: 'Dairy', quantity: 1, expiryDate: format(addDays(today, 14), 'yyyy-MM-dd') },
  { id: 5, name: 'Tomatoes', category: 'Produce', quantity: 5, expiryDate: format(addDays(today, 6), 'yyyy-MM-dd') },
  { id: 6, name: 'Whole Wheat Bread', category: 'Bakery', quantity: 1, expiryDate: format(addDays(today, 4), 'yyyy-MM-dd') },
  { id: 7, name: 'Eggs', category: 'Dairy', quantity: 12, expiryDate: format(addDays(today, 20), 'yyyy-MM-dd') },
  { id: 8, name: 'Spinach', category: 'Produce', quantity: 1, expiryDate: format(addDays(today, 7), 'yyyy-MM-dd') },
];

export const mockRecipes: Recipe[] = [
  {
    id: 1,
    title: 'Spicy Avocado Toast',
    description: 'A quick and delicious breakfast to kickstart your day with a spicy twist.',
    category: 'Quick & Easy',
    country: 'International',
    imageUrl: 'https://picsum.photos/600/400?food=1',
    totalFavorites: 132,
    isFavorite: true,
    ingredients: ['Avocado', 'Bread', 'Chili Flakes'],
    isOwner: true,
  },
  {
    id: 2,
    title: 'Grilled Chicken Salad',
    description: 'A healthy and satisfying salad with perfectly grilled chicken and fresh vegetables.',
    category: 'Halal',
    country: 'American',
    imageUrl: 'https://picsum.photos/600/400?food=2',
    totalFavorites: 250,
    isFavorite: false,
    ingredients: ['Chicken Breast', 'Spinach', 'Tomatoes', 'Avocado'],
  },
  {
    id: 3,
    title: 'Creamy Tomato Soup',
    description: 'A comforting and rich tomato soup that is perfect for a chilly day.',
    category: 'Vegan',
    country: 'Italian',
    imageUrl: 'https://picsum.photos/600/400?food=3',
    totalFavorites: 89,
    isFavorite: false,
    ingredients: ['Tomatoes', 'Vegetable Broth', 'Onion', 'Coconut Cream'],
  },
  {
    id: 4,
    title: 'Classic Tiramisu',
    description: 'An elegant and rich layered Italian dessert made with coffee, mascarpone, and cocoa.',
    category: 'Dessert',
    country: 'Italian',
    imageUrl: 'https://picsum.photos/600/400?food=4',
    totalFavorites: 401,
    isFavorite: true,
    ingredients: ['Eggs', 'Mascarpone', 'Coffee', 'Ladyfingers'],
    isOwner: true,
  },
  {
    id: 5,
    title: 'Cheesy Omelette',
    description: 'A fluffy and cheesy omelette that makes for a perfect and quick breakfast.',
    category: 'Quick & Easy',
    country: 'French',
    imageUrl: 'https://picsum.photos/600/400?food=5',
    totalFavorites: 175,
    isFavorite: false,
    ingredients: ['Eggs', 'Cheddar Cheese', 'Milk'],
  },
  {
    id: 6,
    title: 'Lentil Shepherd\'s Pie',
    description: 'A hearty and wholesome vegan version of the classic Shepherd\'s Pie.',
    category: 'Vegan',
    country: 'International',
    imageUrl: 'https://picsum.photos/600/400?food=6',
    totalFavorites: 210,
    isFavorite: false,
    ingredients: ['Lentils', 'Potatoes', 'Carrots', 'Onion'],
  },
  {
    id: 7,
    title: 'Chicken Biryani',
    description: 'A fragrant and flavorful Indian rice dish with spiced chicken and aromatic basmati rice.',
    category: 'Halal',
    country: 'Indian',
    imageUrl: 'https://picsum.photos/600/400?food=7',
    totalFavorites: 520,
    isFavorite: true,
    ingredients: ['Chicken', 'Basmati Rice', 'Yogurt', 'Spices'],
  },
  {
    id: 8,
    title: 'Chocolate Lava Cake',
    description: 'A decadent and gooey chocolate cake with a molten chocolate center.',
    category: 'Dessert',
    country: 'American',
    imageUrl: 'https://picsum.photos/600/400?food=8',
    totalFavorites: 350,
    isFavorite: false,
    ingredients: ['Chocolate', 'Butter', 'Eggs', 'Sugar'],
    isOwner: true,
  },
];
